---
- hosts: "{{host}}"
  gather_facts: False
  tasks:
  - name: 0. MAKE DIR
    become: yes
    file:
      path: /home/admin/publish/{{project}}/{{module}}/{{ item.sub_dir }}
      group: admin
      owner: admin
      state: absent
    with_items:
      - {sub_dir: "lastest"}