---
# Tomcat version number
tomcat_default_version: '6.0.48'
tomcat_version: "{{ ansible_local['tomcat']['general']['version'] if ansible_local['tomcat'] is defined else tomcat_default_version }}"

# Mirror where to dowload Tomcat redistributable package from
tomcat_mirror: http://mirrors.ejuops.com/softwares/tomcat
# Allow to override where to download Tomcat from
tomcat_download_url: "{{ tomcat_mirror }}/{{ tomcat_filename }}"

# Tomcat installation directories
#   base directory for Tomcat installations
tomcat_install_base: /opt/tomcat


# Default tomcat user when not configured per instance
#   per instance name: item.user
tomcat_default_user_name: admin
#   per instance name: item.group
tomcat_default_user_group: admin
#   per instance name: item.home
tomcat_default_user_home: "/home/{{ tomcat_default_user_name }}"
#   per instance name: item.system
tomcat_default_user_system: false


# Tomcat configuration
#   Default template for configuration file server.xml
tomcat_default_server_xml_template: server.xml.j2
#   Default template for configuration file context.xml
tomcat_default_context_xml_template: context.xml.j2
#   Default template for configuration file web.xml
tomcat_default_web_xml_template: web.xml
#   Default template for log4j.properties
tomcat_default_log4j_properties_template: log4j.properties.j2
#   Default shutdown port (per instance name: item.server_elements.port_shutdown)
tomcat_default_port_shutdown: 8005
#   Default connector port (per instance name: item.server_elements.port_connector)
tomcat_default_port_connector: 8080
#   Default redirect port (per instance name: item.server_elements.port_redirect)
tomcat_default_port_redirect: 8443
#   Default AJP port (per instance name: item.server_elements.port_ajp)
tomcat_default_port_ajp: 8009
#   Default Oracle port
tomcat_default_port_db: 1521
#   Default CATALINA_OPTS (per instance name: item.server_elements.catalina_opts)
tomcat_default_normal_opts: "-server -Xss512k -Dsun.net.inetaddr.ttl=30"
tomcat_default_mem_opts: "-Xmx2g -Xms2g -Xmn1g -XX:PermSize=256m -XX:MaxPermSize=256m"
tomcat_default_gc_opts: "-XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSClassUnloadingEnabled -XX:+PrintTenuringDistribution -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=68 -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+PrintHeapAtGC -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=7 -XX:GCLogFileSize=512M -verbose:gc"
tomcat_default_extra_opts: ""
tomcat_default_debug_opts: "-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=n"
tomcat_default_catalina_opts: ""
#   Default per instance path
tomcat_default_instance_path: /opt/tomcat
# Default log path
tomcat_default_log_base_path: /data/logs
#   Default per instance URI encoding
tomcat_default_override_uri_encoding: ""
#   Whether to prefer IPv4 over IPv6
tomcat_default_prefer_ipv4: true
#   Whether to prefer /dev/urandom over /dev/random
tomcat_default_prefer_urandom: true

tomcat_default_service_dir: /usr/lib/systemd/system

tomcat_default_service_file: tomcat
tomcat_default_service_file_mode: 0755
# tomcat instance(s)
tomcat_instances:

# tomcat_instances_libs
tomcat_instances_libs:
  - { url: "{{ tomcat_mirror }}/extras/ojdbc14-10.2.0.2.0.jar",
      filename: "ojdbc14-10.2.0.2.0.jar",
    }
  - { url: "{{ tomcat_mirror }}/extras/log4j-1.2.13.jar",
      filename: "log4j-1.2.13.jar",
    }


#   template for upstart
tomcat_server_upstart_template: service_upstart.j2
#   template for sysvinit
tomcat_server_sysvinit_template: service_sysvinit.j2
#   template for systemd
tomcat_server_systemd_template: service_systemd.j2


# Whether to allow or deny restarting Tomcat instances automatically
tomcat_service_allow_restart: true

# path to lib_role
tomcat_path_to_lib_role: "{{ lib_roles_path|default(playbook_dir + '/roles') }}"
