---
# This task will have configurable become framework once v2 arrives
- name: util._get
  tags: util
  local_action: get_url
    url={{ url|mandatory }}
    dest={{ dest|mandatory }}
    url_username={{ url_username|default(omit) }}
    url_password={{ url_password|default(omit) }}
    sha1sum={{ sha1sum|default(omit) }}
    force={{ force|default(false) }}
    timeout={{ timeout|default(util_module_get_url_timeout) }}
    use_proxy={{ use_proxy|default(true) }}
    validate_certs={{ validate_certs|default(true) }}
    mode={{ mode|default(0644) }}
    owner={{ util_persistent_data_path_local_owner|default(omit) }}
    group={{ util_persistent_data_path_local_group|default(omit) }}
