---
- hosts: "{{ targets }}"
  vars:
    tomcat_version: 7.0.73
  roles:
    - role: eju.java
    - role: eju.tomcat
      tomcat_instances:
        - name: "{{ module_name }}"
          service_name: "tomcat@{{ module_name }}"
          server_elements:
            shutdown_port: 31125
            resource:
            executors:
            connectors:
              element_1:
                port: 31120
                protocol: org.apache.coyote.http11.Http11NioProtocol
                connectionTimeout: 20000
                maxThreads: 1000
                minSpareThreads: 25
                maxSpareThreads: 75
                enableLookups: false
                URIEncoding: UTF-8
                acceptCount: 1000
                server: Fangjs App Srv 1.0
                redirectPort: 8443
          context_elements:
            Resource:
              element_1:
                name: jdbc/ds_msg2
                auth: Container
                factory: com.netfinworks.inf.dbcp.EncryptedDataSourceFactory
                type: javax.sql.DataSource
                driverClassName: oracle.jdbc.OracleDriver
                url: jdbc:oracle:thin:@//10.106.143.1:1521/fjsdb
                username: msg2user
                password: HiY3hi6dl
                initialSize: 20
                maxActive: 50
                maxIdle: 20
                minIdle: 20
                validationQuery: select 1 from dual
                testOnBorrow: true
                testOnReturn: true
                testWhileIdle: true
                timeBetweenEvictionRunsMillis: 600000
                numTestsPerEvictionRun: 10
                minEvictableIdleTimeMillis: 21600000
                maxWait: 900
              element_2:
                name: jms/jmsConnectionFactory
                auth: Container
                type: org.apache.activemq.ActiveMQConnectionFactory
                description: JMS Connection Factory
                factory: org.apache.activemq.jndi.JNDIReferenceFactory
                brokerURL: failover:(tcp://10.120.142.205:61616,tcp://10.120.142.206:61616)?jms.useAsyncSend=true
                userName: fjsadmin
                password: Fjs@201702
              element_3:
                name: jms/queue/jmsproxy_basefacade
                auth: Container
                type: org.apache.activemq.command.ActiveMQQueue
                description: My Queue
                factory: org.apache.activemq.jndi.JNDIReferenceFactory
                physicalName: jmsproxy_basefacade
              element_4:
                name: jms/queue/jmsproxy_msg2Facade
                auth: Container
                type: org.apache.activemq.command.ActiveMQQueue
                description: My Queue
                factory: org.apache.activemq.jndi.JNDIReferenceFactory
                physicalName: jmsproxy_msg2Facade