---
- hosts: "{{host}}"
  gather_facts: False
  tasks:
  - name: 0.1 MAKE DIR
    file:
      path: /home/admin/publish/{{project}}/{{module}}/{{ item.sub_dir }}
      group: admin
      owner: admin
      state: directory 
    with_items:
      - {sub_dir: "lastest"}
  - name: 0.2 MAKE DIR
    delegate_to: localhost
    file:
      path: "/home/admin/publish/files/{{env}}/{{project}}/{{module}}/{{version}}/{{build}}/"
      group: admin
      owner: admin
      state: directory 
  - name: 0.3 DOWNLOAD VERSION
    delegate_to: localhost
    get_url:
      url: "{{item.file_url}}"
      dest: "/home/admin/publish/files/{{env}}/{{project}}/{{module}}/{{version}}/{{build}}/{{item.file_name}}"
      checksum: "md5:{{item.md5}}"
      force: no
    with_items: "{{ file_list }}"
  - name: 1. TRANSFER VERSION
    synchronize: 
      src: "{{item.src}}" 
      dest: "{{item.dest}}" 
      use_ssh_args: yes
      delete: yes
    with_items:
      - {src: "/home/admin/publish/files/{{env}}/{{project}}/{{module}}/{{version}}/{{build}}/", dest: "/home/admin/publish/{{project}}/{{module}}/lastest/"}
  - name: 2. STOP SERVICE
    become: yes
    service:
      name: "tomcat@{{module}}"
      state: stopped
  - name: 3. RUN UPDATE SCRIPT
    script: '{{ ansible_resource_dir }}/scripts/{{project}}/{{module}}/update.sh {{env}} {{project}} {{module}} {{version}} {{build}}'
  - name: 4. START SERVICE
    become: yes
    service:
      name: "tomcat@{{module}}"
      state: started

