---
- hosts: "{{ module_name }}"
  roles:
    - role: eju.java
    - role: eju.tomcat
      tomcat_instances:
        - name: "{{ module_name }}"
          service_name: "tomcat@{{ module_name }}"
          server_elements:
            shutdown_port: 10101
            resource:
            executors:
              name: tomcatThreadPool
              namePrefix: tomcat-threads--
              maxThreads: 1500
              minSpareThreads: 50
            connectors:
              element_1:
                acceptCount: 200
                port: 8401
                protocol: HTTP/1.1
                executor: tomcatThreadPool
                enableLookups: false
                connectionTimeout: 20000
                maxKeepAliveRequests: 15
                minProcessors: 20
                maxProcessors: 200
                redirectPort: 8701
                disableUploadTimeout: true
                URIEncoding: utf-8
                useBodyEncodingForURI: true
              element_2:
                acceptCount: 200
                port: 8301
                protocol: AJP/1.3
                executor: tomcatThreadPool
                enableLookups: false
                connectionTimeout: 20000
                maxKeepAliveRequests: 15
                minProcessors: 20
                maxProcessors: 200
                redirectPort: 8701
                disableUploadTimeout: true
          context_elements:
            Resource:
              element_1:
                name: jdbc/ds_planner
                auth: Container
                type: javax.sql.DataSource
                driverClassName: oracle.jdbc.OracleDriver
                url: jdbc:oracle:thin:@//10.120.132.52:1521/env
                username: planner
                password: planner
                initialSize: 20
                maxActive: 2000
                maxIdle: 20
                minIdle: 20
                validationQuery: select 1 from dual
                testOnBorrow: true
                testOnReturn: true
                testWhileIdle: true
                timeBetweenEvictionRunsMillis: 600000
                numTestsPerEvictionRun: 10
                minEvictableIdleTimeMillis: 21600000
                maxWait: 900
