---
- hosts: "{{host}}"
  gather_facts: False
  tasks:
  - name: 1. MAKE DIR
    file:
      path: /home/admin/publish/{{project}}/{{module}}/{{ item.sub_dir }}
      group: admin
      owner: admin
      state: directory 
    with_items:
      - {sub_dir: "lastest"}
      - {sub_dir: "script"}
  - name: 3. RUN UPDATE SCRIPT
    script: '{{ ansible_resource_dir }}/scripts/{{project}}/{{module}}/update.sh {{env}} {{project}} {{module}} {{version}} {{build}}'

