- hosts: "msg2-inrpc"
  roles:
    - role: eju.java 
    - role: eju.tomcat 
      deploy_module: 
        name: msg2-inrpc
        port_shutdown: 10106
        port_connector: 8406
        port_redirect: 8706
        port_ajp: 8306
        ip_db: 10.120.132.46
        port_db: 1521
        db_name: test_yml
  tasks:
    - name: INSTALL SPECIAL FILES
      synchronize:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
        use_ssh_args: yes
        delete: yes
      with_items:
        - {src: "/home/admin/ansible/data/jpol/msg2-inrpc/lib/", dest: "/opt/tomcat/msg2-inrpc/lib/"}
    - name: RESTART
      become: true
      service:
        state: restarted
        name: tomcat@msg2-inrpc
