---
- hosts: "mb-inrpc"
  roles:
    - role: eju.java 
    - role: eju.tomcat 
      deploy_module: 
        name: mb-inrpc
        port_shutdown: 10012
        port_connector: 8112
        port_redirect: 8512
        port_ajp: 8212
        ip_db: 10.120.132.46
        port_db: 1521
        db_name: test_yml
  tasks:
    - name: INSTALL SPECIAL FILES
      synchronize:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
        use_ssh_args: yes
        delete: yes
      with_items:
        - {src: "/home/admin/ansible/data/jpol/mb-inrpc/lib/", dest: "/opt/tomcat/mb-inrpc/lib/"}
    - name: RESTART
      become: true
      service:
        state: restarted
        name: tomcat@mb-inrpc
