---
- hosts: "{{host}}"
  gather_facts: False
  tasks:
  - name: 1. ONLINE HOST
    file:
      path: /home/admin/publish/{{project}}/{{module}}/{{ item.sub_dir }}
      group: admin
      owner: admin
      state: directory 
    with_items:
      - {sub_dir: "lastest"}

