---
- hosts: "{{host}}"
  gather_facts: False
  tasks:
  - name: 0.1 MAKE DIR
    file:
      path: /home/admin/publish/{{project}}/{{module}}/{{ item.sub_dir }}
      group: admin
      owner: admin
      state: directory 
    with_items:
      - {sub_dir: "lastest"}
  - name: 0.2 MAKE DIR
    delegate_to: localhost
    file:
      path: "/home/admin/publish/files/{{env}}/{{project}}/{{module}}/{{version}}/{{build}}/"
      group: admin
      owner: admin
      state: directory
  - name: 1. DOWNLOAD VERSION
    delegate_to: localhost
    get_url:
      url: "{{item.file_url}}"
      dest: "/home/admin/publish/files/{{env}}/{{project}}/{{module}}/{{version}}/{{build}}/{{item.file_name}}"
      checksum: "md5:{{item.md5}}"
      force: no
    with_items: "{{ file_list }}"
  - name: 2. TRANSFER VERSION
    unarchive:
      src: "/home/admin/publish/files/{{env}}/{{project}}/{{module}}/{{version}}/{{build}}/{{item.file_name}}"
      dest: "/home/admin/publish/{{project}}/{{module}}/lastest"
      remote_src: no
    with_items: "{{ file_list }}"
  - name: 3. STOP SERVICE
    shell: chdir=/opt/node/ source ./stop.sh 
  - name: 4. RUN UPDATE SCRIPT
    script: '{{ ansible_resource_dir }}/scripts/{{project}}/{{module}}/update.sh {{env}} {{project}} {{module}} {{version}} {{build}}'
  - name: 5. START SERVICE
    shell: chdir=/opt/node source ./start.sh 

